global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: /metrics
    static_configs:
      - targets:
          - fastapi:8000
        labels:
          service: flight-delay-api

  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - cadvisor:8080
        labels:
          service: containers

  - job_name: 'prometheus'
    static_configs:
      - targets:
          - localhost:9090
